name: CI - SecureCart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r securecart/requirements.txt

    - name: Run Django checks
      run: |
        python securecart/manage.py check

    - name: Run Snyk SAST scan
      uses: snyk/actions/python@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=securecart/requirements.txt --package-manager=pip

    - name: Save Snyk results
      run: echo "Snyk scan completed"