# This GitHub Actions workflow implements SecureCart's CI pipeline.
# It installs dependencies, sets up Python 3.12, and performs SAST using Snyk.
# For more details, see Section 5.4 of the submitted coursework report.
name: SecureCart CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r securecart/requirements.txt

    - name: Run Snyk SAST scan
      uses: snyk/actions/python@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=securecart/requirements.txt --package-manager=pip
